Added Api for the tournaments
Aditya-Thakur/MetaClassicAPI pull request #1
Opened 2022-06-11 16:29 UTC by AayushSaini101

Added Api for the tournaments

2022-06-11 17:48 UTC, merged

2022-06-11 17:54 UTC, Aditya-Thakur requested changes
Please go through the comments and update it.

2022-06-11 17:54 UTC, Aditya-Thakur commented on controller/tournamentController.js
> +function viewTournamentDetails(req, res) {
change it to viewAllTournament

2022-06-11 17:54 UTC, Aditya-Thakur commented on controller/tournamentController.js
> +    tournament.findOne({ tournamentId: req.body.tournamentId }, function(err, tournament) {
This function needs to be like this: 
function should get userId & tournamentId. 
It should update both user & tournament collection

2022-06-11 17:54 UTC, Aditya-Thakur commented on controller/tournamentController.js
> +const user = mongoose.model('User');
require tournament here not user

2022-06-11 17:54 UTC, Aditya-Thakur commented on controller/tournamentController.js
> +    console.log('need to register ', req.body.email);
remove this log since you are using logger

2022-06-11 17:57 UTC, Aditya-Thakur commented
Raise another PR after changes.

2022-06-12 06:02 UTC, AayushSaini101 commented
Okay Sir